# Generated by Django 3.0.7 on 2020-06-25 16:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0002_sportnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 25, 16, 33, 56, 829475, tzinfo=utc)),
        ),
    ]
